// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDlv-_stL0YT06-fE0EtmxIhUAnUJEHTRo",
      authDomain: "shop-43627.firebaseapp.com",
      databaseURL: "https://shop-43627-default-rtdb.firebaseio.com",
      projectId: "shop-43627",
      storageBucket: "shop-43627.firebasestorage.app",
      messagingSenderId: "826976886349",
      appId: "1:826976886349:web:979a581c2062c9babe0604",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbefiPltzdelJQLyOxXynZE1hJuq0uYg',
    appId: '1:826976886349:android:581ad270ca8815c5be0604',
    messagingSenderId: '826976886349',
    projectId: 'shop-43627',
    databaseURL: 'https://shop-43627-default-rtdb.firebaseio.com',
    storageBucket: 'shop-43627.firebasestorage.app',
  );

}